import localFont from "next/font/local";
import "./globals.css";
import Navbar from '@/components/navbar';  // Import the Navbar
import Footer from '@/components/footer';  // Import the Footer

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Contract Farming",
  description: "Generated by Team VIZION",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}>
        {/* Navbar always at the top */}
        <Navbar />

        {/* Main content area takes up the remaining space */}
        <main className="flex-grow">{children}</main>

        {/* Footer always at the bottom */}
        <Footer />
      </body>
    </html>
  );
}
